//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmdhGui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmdhGui.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Arguments.
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes Delta.
        /// </summary>
        public static string BytesDelta {
            get {
                return ResourceManager.GetString("BytesDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clea_n Output Directory.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Delta.
        /// </summary>
        public static string CountDelta {
            get {
                return ResourceManager.GetString("CountDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Database Size.
        /// </summary>
        public static string DatabaseSize {
            get {
                return ResourceManager.GetString("DatabaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Size (MB).
        /// </summary>
        public static string DbSize {
            get {
                return ResourceManager.GetString("DbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use this process: {0}.
        /// </summary>
        public static string ErrorSelectProcess {
            get {
                return ResourceManager.GetString("ErrorSelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Executable.
        /// </summary>
        public static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack contains.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterGroup {
            get {
                return ResourceManager.GetString("FilterGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First snapshot.
        /// </summary>
        public static string FirstSnapshot {
            get {
                return ResourceManager.GetString("FirstSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFlags.
        /// </summary>
        public static string GFlags {
            get {
                return ResourceManager.GetString("GFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Execution Options.
        /// </summary>
        public static string ImageFileExecutionOptions {
            get {
                return ResourceManager.GetString("ImageFileExecutionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Image Name.
        /// </summary>
        public static string ImageName {
            get {
                return ResourceManager.GetString("ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bytes.
        /// </summary>
        public static string NewBytes {
            get {
                return ResourceManager.GetString("NewBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Count.
        /// </summary>
        public static string NewCount {
            get {
                return ResourceManager.GetString("NewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Bytes.
        /// </summary>
        public static string OldBytes {
            get {
                return ResourceManager.GetString("OldBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Count.
        /// </summary>
        public static string OldCount {
            get {
                return ResourceManager.GetString("OldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output Directory.
        /// </summary>
        public static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessCaption {
            get {
                return ResourceManager.GetString("ProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with OANOCACHE.
        /// </summary>
        public static string RunOaNoCache {
            get {
                return ResourceManager.GetString("RunOaNoCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Process with OANOCACHE.
        /// </summary>
        public static string RunOaNoCacheTitle {
            get {
                return ResourceManager.GetString("RunOaNoCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second snapshot.
        /// </summary>
        public static string SecondSnapshot {
            get {
                return ResourceManager.GetString("SecondSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process.
        /// </summary>
        public static string SelectProcessTitle {
            get {
                return ResourceManager.GetString("SelectProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string SnapshotGroup {
            get {
                return ResourceManager.GetString("SnapshotGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Symbol Path.
        /// </summary>
        public static string SymbolPath {
            get {
                return ResourceManager.GetString("SymbolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take.
        /// </summary>
        public static string Take {
            get {
                return ResourceManager.GetString("Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umdh Gui.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ToolDirectory.
        /// </summary>
        public static string ToolDirectory {
            get {
                return ResourceManager.GetString("ToolDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case insensitive substrings that have to be in the stack trace. You can separate multiple substrings with a ;.
        /// </summary>
        public static string TooltipFilter {
            get {
                return ResourceManager.GetString("TooltipFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This warning means that a symbol path different from the _NT_SYMBOL_PATH is used..
        /// </summary>
        public static string TooltipShowSymbolPathOverrideWarning {
            get {
                return ResourceManager.GetString("TooltipShowSymbolPathOverrideWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceId.
        /// </summary>
        public static string TraceId {
            get {
                return ResourceManager.GetString("TraceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umdh.
        /// </summary>
        public static string Umdh {
            get {
                return ResourceManager.GetString("Umdh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode Stacktrace Database.
        /// </summary>
        public static string UserModeStacktraceDatabase {
            get {
                return ResourceManager.GetString("UserModeStacktraceDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mode Stack 
        ///Trace Database.
        /// </summary>
        public static string UstEnabled {
            get {
                return ResourceManager.GetString("UstEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Write.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
    }
}
